security:
    encoders:
        App\Entity\TAdmin:
            algorithm: auto
        App\Entity\TShopUser:
            algorithm: auto
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_admin_provider:
            entity:
                class: App\Entity\TAdmin
                property: adLogin
        app_user_provider:
            entity:
                class: App\Entity\TShopUser
                property: uEmail
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:   ^/administrateur
            lazy: true
            provider: app_admin_provider
            custom_authenticator:
                - App\Security\AdminFormAuthenticator
            logout:
                path: app_logout
                target: administrateur

        user:
            pattern:   ^/
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - App\Security\UserFormAuthenticator
            logout:
                path: app_logout
                target: changeUserPanier



            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/administrateur/, roles: ROLE_ADMIN }
         - { path: ^/membre, roles: ROLE_USER }
         - { path: ^/commande, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }
