index:
    path: /
    controller: App\Controller\DefaultController::index
boutique:
    path: /boutique
    controller: App\Controller\DefaultController::boutique
produit:
    path: /produit
    controller: App\Controller\DefaultController::produit
login:
    path: /connexion
    controller: App\Controller\DefaultController::login
register:
    path: /inscription
    controller: App\Controller\DefaultController::register
contact:
    path: /contact
    controller: App\Controller\DefaultController::contact
panier:
    path: /panier
    controller: App\Controller\DefaultController::panier
membre:
    path: /membre
    controller: App\Controller\DefaultController::membre


admin:
    path: /admin
    controller: App\Controller\DefaultController::admin
admin_boutique:
    path: /admin/admin_produit
    controller: App\Controller\DefaultController::admin_produit
